### ISSUE TITLE
HTTP API support

### ISSUE THREAD

**Issue by juanludlf** [dougmoscrop/serverless-plugin-split-stacks#110]
Hi,

I'm getting the cloudformation limit exception when I try to deploy a HTTP API API Gateway:

- `Number of resources, 227, is greater than maximum allowed, 200`

```$ sls deploy
Serverless: Packaging service...
Serverless: Recoverable error occurred (Rate exceeded), sleeping for ~6 seconds. Try 1 of 4
Serverless: Recoverable error occurred (Rate exceeded), sleeping for ~4 seconds. Try 1 of 4
Serverless: [serverless-plugin-split-stacks]: Summary: 120 resources migrated in to 30 nested stacks
Serverless: [serverless-plugin-split-stacks]:    Resources per stack:    
Serverless: [serverless-plugin-split-stacks]:    - (root): 227
Serverless: [serverless-plugin-split-stacks]:    - AdsNestedStack: 4     
Serverless: [serverless-plugin-split-stacks]:    - CenterNestedStack: 4  
Serverless: [serverless-plugin-split-stacks]:    - CityNestedStack: 4    
Serverless: [serverless-plugin-split-stacks]:    - CountryNestedStack: 4 
Serverless: [serverless-plugin-split-stacks]:    - FileNestedStack: 4
...
```

Am I doing something wrong? 
How can I decrease the number of resources in the root stack while keeping the number of routes of my API?
I have already tried deploy the stack from scratch

Thanks!

**Comment by dougmoscrop** [comment]
This project is (probably overly) conservative, and so it won't deploy most resources, you gotta use a stacks-map.js file (its in the docs) to migrate resources yourself. If you find resources that can easily always be migrated, PRs are welcome to add them to the list, I just started with a pretty minimal set.

**Comment by juanludlf** [comment]
Thank you @dougmoscrop, I solved it using stacks-map

```
$ sls deploy
Serverless: Packaging service...
Serverless: [serverless-plugin-split-stacks]: Summary: 309 resources migrated in to 31 nested stacks
Serverless: [serverless-plugin-split-stacks]:    Resources per stack:
Serverless: [serverless-plugin-split-stacks]:    - (root): 39
Serverless: [serverless-plugin-split-stacks]:    - AdsNestedStack: 7
Serverless: [serverless-plugin-split-stacks]:    - AlertNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - BrowserNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - CenterNestedStack: 8
Serverless: [serverless-plugin-split-stacks]:    - CityNestedStack: 7
Serverless: [serverless-plugin-split-stacks]:    - CountryNestedStack: 8
...
```

**Comment by dougmoscrop** [comment]
Nice! I also encourage you to check out my other plugin, serverless-plugin-bootstrap, which I advise to use to store things like your database or queues etc. -- things that persist data, that change infrequently. It's useful because sometimes you just have to `sls remove` your application stack and redepoy it, it sucks, it has downtime, but if you use a bootstrap layer (the name.. not the best, I know) you can avoid data loss.
