### ISSUE TITLE
Hey everyone, AWS has announced that CloudFormation now supports increased limits on five service quotas

### ISSUE THREAD

**Issue by LinguineCode** [dougmoscrop/serverless-plugin-split-stacks#141]
This news greatly impacts this plugin

## AWS CloudFormation now supports increased limits on five service quotas

> Posted On: Oct 22, 2020
> 
> AWS CloudFormation now supports increased limits on five service quotas - template size, resources, parameters, mappings, and outputs. The maximum size of a template that can be passed in an S3 Object is now 1MB (previously 450KB). The new per template limits for the maximum number of resources is 500 (previously 200), parameters is 200 (previously 60), mappings is 200 (previously 100), and outputs is 200 (previously 60).

> CloudFormation allows you to model and provision cloud resources as code in a safe, predictable, and scalable manner. With this launch, you can model large applications with up to 500 resources in a single template. A larger template size lets you include more of your application code within the template, such as user data to bootstrap your EC2 instances so that your templates are self-contained. Support for more parameters and mappings increases the reusability of your templates within your organization. Now you can create more versatile templates that can be used across accounts and regions. With an 

> increased output limit, you can export more values for use in other templates or check intermediate values created within the template without leaving the CloudFormation console. To get started, read our AWS CloudFormation quotas documentation.
These service quota limit increases are available in all regions that support CloudFormation, at no additional charge. For CloudFormation region availability, refer to the AWS Region Table.

https://aws.amazon.com/about-aws/whats-new/2020/10/aws-cloudformation-now-supports-increased-limits-on-five-service-quotas/

**Comment by richarddd** [comment]
Yes, so how can we "revert" adding split stacks?

**Comment by gregholland** [comment]
I managed to remove it with only a couple of mins downtime on my HTTP endpoint triggered functions, and no downtime on my stream triggered functions.
- Temporarily removing all functions triggered by HTTP events from my `serverless.yml` (any triggered by streams can stay)
- Deploy to stage
- Put all removed functions back and deploy to stage

Not ideal having any downtime, but if you can afford a couple of minutes, it works.
