### ISSUE TITLE
error: Template error: RootResourceId attribute of API Gateway RestAPI xxxx doesn't exist.

### ISSUE THREAD

**Issue by kim00425** [dougmoscrop/serverless-plugin-split-stacks#185]
nothing has been specifically modified. before that, the distribution was good. 

when deploy start, some stacks are failed and show message Template error: RootResourceId attribute of API Gateway RestAPI 2eg9uz9839 doesn't exist.

what should i check? 

serverless-plugin-split-stacks: 1.11.0
serverless: 1.83.3
serverless-layers: 2.4.0

**Comment by ElNinjaGaiden** [comment]
Any update on this? I also started to get this error a some of weeks ago with no relevant changes.

serverless-plugin-split-stacks: 1.11.3
serverless: 2.69.0

**Comment by kim00425** [comment]
@ElNinjaGaiden  i solve this problem. just increase my resourceConcurrency. i used 60 when i change to 80. i can deploy and again.
i think nestedStack need rootResourceId. 
so i recommend step2 below link
https://seed.run/blog/how-to-share-an-api-domain-between-services-in-a-monorepo-serverless-app.html
