### ISSUE TITLE
Circular dependency with perGroupFunction and resourceConcurrency

### ISSUE THREAD

**Issue by sweepy84** [dougmoscrop/serverless-plugin-split-stacks#188]
There seems to be a bug in how resource concurrency is implemented with perGroupFunction strategy or custom splitting using stacks-map.js.

It is very easy to replicate - just use those 2 features together.

 https://github.com/dougmoscrop/serverless-plugin-split-stacks/issues/122#issuecomment-947051119

**Comment by sweepy84** [comment]
Btw this happens also with custom splitting strategy (not just perGroupFunction) and possibly other scenarios. When resources are moved to a nested stack and resourceConcurrency is on.

**Comment by turakvlad** [comment]
@sweepy84 , I see you closed this issue. Did you manage to find any solution?

We have the same problem. I described it here https://github.com/dougmoscrop/serverless-plugin-split-stacks/issues/122#issuecomment-2022266459.
