### ISSUE TITLE
Using the plugin

### ISSUE THREAD

**Issue by seanjb** [dougmoscrop/serverless-plugin-split-stacks#2]
Hi there,
Are there any special commands or config needed to use this other than installing the plugin and referencing it in serverless.yml?

Did just that and noticed no difference on running `sls deploy`
From running it without the plugin (aka stack did not split)

**Comment by dougmoscrop** [comment]
That should be it; are you using a newer version of Serverless? This plugin relies on the "internal lifecycle events" stuff (e.g. `aws:deploy:deploy:uploadArtifacts`) that didn't exist until I think ~1.13?

Also it's possible you don't have any resources that are candidates for splitting. This plugin has like an explicit list of things that it tries to migrate, vs. trying to migrate anything and everything (just too much blew up when doing it that way).

I don't have great debugging in here, sorry  (PRs welcome) but this should print a summary about the # of resources and the # of stacks (see https://github.com/dougmoscrop/serverless-plugin-split-stacks/blob/master/lib/log-summary.js for the format).

Do you see this message at all?

**Comment by seanjb** [comment]
Whoops was on Serverless v 1.10. Updating fixed the issue
