### ISSUE TITLE
Support Serverless's `--minify-template` flag

### ISSUE THREAD

**Issue by Kycermann** [dougmoscrop/serverless-plugin-split-stacks#209]
Serverless kindly merged my PR (https://github.com/serverless/serverless/pull/11980) to add a `--minify-template` flag to the library. This flag, when set, causes templates to be written as minified JSON instead of prettidied JSON.

However, since this plugin uses the Serverless util writeFileSync, it does not minify the templates. I would be happy to open a PR to add support for the `--minify-template` flag to this plugin, if you're happy to merge the PR.

Let me know please.

**Comment by dougmoscrop** [comment]
Sure, go for it
