### ISSUE TITLE
Formidable arbitrary file upload 

### ISSUE THREAD

**Issue by barbasaviles** [dougmoscrop/serverless-plugin-split-stacks#216]
Hello, could you please update the library that was detected as a vulnerability?

https://github.com/advisories/GHSA-8cp3-66vr-3r4c

![image](https://github.com/dougmoscrop/serverless-plugin-split-stacks/assets/46799302/bb999216-5539-49d4-b45a-51a000b3c0ad)

**Comment by dougmoscrop** [comment]
the CVE isn't relevant in this context, and and comes from the version of serverless you're using, which is a peerDependency
