### ISSUE TITLE
serverSideEncryption error in 1.4.0

### ISSUE THREAD

**Issue by ogreface** [dougmoscrop/serverless-plugin-split-stacks#26]
With nothing changing in our serverless.yml function, going from 1.3.2 to 1.4.0 makes deployments fail. Specific error message is below, but it appears to be that the code is expecting certain variables? We've pinned the version to 1.3.2 for now.r

Thanks for the help/plugin!

 

>  Type Error ---------------------------------------------
> 
>   Cannot read property 'serverSideEncryption' of undefined
> 
>      For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
> 
>   Stack Trace --------------------------------------------
> 
> TypeError: Cannot read property 'serverSideEncryption' of undefined
>     at encryptionFields.reduce (/home/travis/build/StediInc/platform-api-service/node_modules/serverless-plugin-split-stacks/lib/utils.js:289:33)
>     at Array.reduce (<anonymous>)
>     at ServerlessPluginSplitStacks.getEncryptionParams (/home/travis/build/StediInc/platform-api-service/node_modules/serverless-plugin-split-stacks/lib/utils.js:288:29)
>     at Promise.all._.map.file (/home/travis/build/StediInc/platform-api-service/node_modules/serverless-plugin-split-stacks/split-stacks.js:92:43)
>     at arrayMap (/home/travis/build/StediInc/platform-api-service/node_modules/lodash/lodash.js:631:23)
>     at Function.map (/home/travis/build/StediInc/platform-api-service/node_modules/lodash/lodash.js:9546:14)
>     at provider.getServerlessDeploymentBucketName.then.deploymentBucket (/home/travis/build/StediInc/platform-api-service/node_modules/serverless-plugin-split-stacks/split-stacks.js:83:30)
> From previous event:
>     at ServerlessPluginSplitStacks.upload (/home/travis/build/StediInc/platform-api-service/node_modules/serverless-plugin-split-stacks/split-stacks.js:80:8)
>     at BbPromise.reduce (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
> From previous event:
>     at PluginManager.invoke (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
>     at PluginManager.spawn (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/classes/PluginManager.js:390:17)
>     at AwsDeploy.BbPromise.bind.then (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:101:48)
> From previous event:
>     at Object.deploy:deploy [as hook] (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:97:10)
>     at BbPromise.reduce (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
> From previous event:
>     at PluginManager.invoke (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
>     at PluginManager.run (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/classes/PluginManager.js:403:17)
>     at variables.populateService.then (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/Serverless.js:102:33)
>     at runCallback (timers.js:789:20)
>     at tryOnImmediate (timers.js:751:5)
>     at processImmediate [as _immediateCallback] (timers.js:722:5)
> From previous event:
>     at Serverless.run (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/Serverless.js:89:74)
>     at serverless.init.then (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/bin/serverless:42:50)
>     at <anonymous>

**Comment by dougmoscrop** [comment]
Shit, sorry, typo on my part. I added tests to guard against it and fixed in 1.4.1

**Comment by ogreface** [comment]
Tested, and 1.4.1 fixes the issue. Thanks for the quick fix!
