### ISSUE TITLE
How to Remove & Deploy only one nested stack ?!

### ISSUE THREAD

**Issue by bzemms** [dougmoscrop/serverless-plugin-split-stacks#29]

**Comment by dougmoscrop** [comment]
Can you elaborate on your use case more? The work being done @medikoo is the "vision" for this plugin which is that each function lives in it's own nested stack. This means that a stack goes away when the function goes away, and you have as many stacks as you have functions (meaning there is an upper bound on the number of functions).

In the current version, nested stacks are created when they are needed. Removing them would happen when there's no resources left to put in them (unless there is a bug).

However, there's no way to "compact" stacks; once a resource is migrated, it needs to stay in the same stack. Moving resources between stacks can work but can also be impossible depending on the resource type.

**Comment by bzemms** [comment]
In our sls we have all DynamoDB table grouped in one nested stack, and when we try to modify a table we have to `sls remove` all nested stacks.

The question was, how can we delete and redeploy only the dynamo stack, since update dnamo tabels is not working

**Comment by dougmoscrop** [comment]
I'm not _sure_ I understand the use case, so please re-open if I am wrong, but I don't think this is in the realm of what this plugin is intended for. As @medikoo pointed out, you can remove any resources you want. This plugin just decides where they go.
