### ISSUE TITLE
Cannot Push to a new branch with proposed changes

### ISSUE THREAD

**Issue by AyushG3112** [dougmoscrop/serverless-plugin-split-stacks#3]
Now to GIT, so sorry if I'm making a newbie mistake.

I made some changes in the migrate-resources.js and have been trying to push, but I get the error

> remote: Permission to dougmoscrop/serverless-plugin-split-stacks.git denied to AyushG3112.
> fatal: unable to access 'https://github.com/dougmoscrop/serverless-plugin-split-stacks.git/': The requested URL returned error: 403

Could you provide me access to push my branch so I can open a PR

**Comment by dougmoscrop** [comment]
Hey thanks for your help.

What you want to do is `fork` the repository (top right of the screen), and then that will be a copy under your name/account and you will have full write access to it and can do whatever you want.

Then you can open a pull request between the forks.

**Comment by AyushG3112** [comment]
Ah, gotcha thanks!
