### ISSUE TITLE
Missing required key 'StackName' in params

### ISSUE THREAD

**Issue by chrroo7** [dougmoscrop/serverless-plugin-split-stacks#36]
Serverless Error ---------------------------------------
 
  Missing required key 'StackName' in params

**Comment by dougmoscrop** [comment]
Are you still experiencing this problem? If so, please reopen with more details like `SLS_DEBUG=*` and version numbers of just about everything, other plugins being used. 1.5.5 should be working now in this regard.

**Comment by chrroo7** [comment]
Thank you Doug. I haven't validated the new version, let me try it out.

**Comment by agtcovert** [comment]
I'm still experiencing this problem.
Serverless 1.32
serverless-aws-resource-names: 0.0.9
serverless-dependson-plugin: 1.1.1
serverless-plugin-split-stacks: ^1.6.0
serverless-plugin-tracing: 2.0.0

SLS_DEBUG:
`[AWS CodeBuild Plugin]   Serverless Error ---------------------------------------
[AWS CodeBuild Plugin]  
[AWS CodeBuild Plugin]   Missing required key 'StackName' in params
[AWS CodeBuild Plugin]  
[AWS CodeBuild Plugin]   Stack Trace --------------------------------------------
[AWS CodeBuild Plugin]  
[AWS CodeBuild Plugin] ServerlessError: Missing required key 'StackName' in params
[AWS CodeBuild Plugin]     at BbPromise.fromCallback.catch.err (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:270:11)
[AWS CodeBuild Plugin] From previous event:
[AWS CodeBuild Plugin]     at persistentRequest (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:253:13)
[AWS CodeBuild Plugin]     at doCall (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:205:9)
[AWS CodeBuild Plugin]     at BbPromise (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:222:14)
[AWS CodeBuild Plugin] From previous event:
[AWS CodeBuild Plugin]     at persistentRequest (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:203:38)
[AWS CodeBuild Plugin]     at Object.request.requestQueue.add [as promiseGenerator] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:243:49)
[AWS CodeBuild Plugin]     at Queue._dequeue (/usr/local/lib/node_modules/serverless/node_modules/promise-queue/lib/index.js:153:30)
[AWS CodeBuild Plugin]     at /usr/local/lib/node_modules/serverless/node_modules/promise-queue/lib/index.js:109:18
[AWS CodeBuild Plugin] From previous event:
[AWS CodeBuild Plugin]     at Queue.add (/usr/local/lib/node_modules/serverless/node_modules/promise-queue/lib/index.js:94:16)
[AWS CodeBuild Plugin]     at AwsProvider.request (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:243:39)
[AWS CodeBuild Plugin]     at listStackResources (/codebuild/output/src607015172/src/node_modules/serverless-plugin-split-stacks/lib/utils.js:276:23)
[AWS CodeBuild Plugin]     at ServerlessPluginSplitStacks.getStackSummary (/codebuild/output/src607015172/src/node_modules/serverless-plugin-split-stacks/lib/utils.js:298:12)
[AWS CodeBuild Plugin]     at Promise.all.nestedStacks.map.stack (/codebuild/output/src607015172/src/node_modules/serverless-plugin-split-stacks/lib/migrate-existing-resources.js:21:21)
[AWS CodeBuild Plugin]     at /codebuild/output/src607015172/src/node_modules/throat/index.js:11:22
[AWS CodeBuild Plugin]     at new Promise (/usr/local/lib/node_modules/serverless/node_modules/core-js/modules/es6.promise.js:177:7)
[AWS CodeBuild Plugin]     at run (/codebuild/output/src607015172/src/node_modules/throat/index.js:10:22)
[AWS CodeBuild Plugin]     at /codebuild/output/src607015172/src/node_modules/throat/index.js:49:16
[AWS CodeBuild Plugin]     at Array.map (native)
[AWS CodeBuild Plugin]     at getStackSummary.catch.then.then.nestedStacks (/codebuild/output/src607015172/src/node_modules/serverless-plugin-split-stacks/lib/migrate-existing-resources.js:17:39)
[AWS CodeBuild Plugin]     at runCallback (timers.js:570:20)
[AWS CodeBuild Plugin]     at tryOnImmediate (timers.js:550:5)
[AWS CodeBuild Plugin]     at processImmediate [as _immediateCallback] (timers.js:529:5)
[AWS CodeBuild Plugin] From previous event:
[AWS CodeBuild Plugin]     at ServerlessPluginSplitStacks.getCurrentState [as migrateExistingResources] (/codebuild/output/src607015172/src/node_modules/serverless-plugin-split-stacks/lib/migrate-existing-resources.js:16:6)
[AWS CodeBuild Plugin]     at Promise.resolve.then (/codebuild/output/src607015172/src/node_modules/serverless-plugin-split-stacks/split-stacks.js:57:24)
[AWS CodeBuild Plugin]     at run (/usr/local/lib/node_modules/serverless/node_modules/core-js/modules/es6.promise.js:75:22)
[AWS CodeBuild Plugin]     at /usr/local/lib/node_modules/serverless/node_modules/core-js/modules/es6.promise.js:92:30
[AWS CodeBuild Plugin]     at flush (/usr/local/lib/node_modules/serverless/node_modules/core-js/modules/_microtask.js:18:9)
[AWS CodeBuild Plugin]     at _combinedTickCallback (internal/process/next_tick.js:67:7)
[AWS CodeBuild Plugin]     at process._tickDomainCallback (internal/process/next_tick.js:122:9)`

**Comment by troybESM** [comment]
I have the same issue. Same Serverless and split-stacks version too.

**Comment by dougmoscrop** [comment]
Hmm, this is strange, I wonder if it's some kind of race condition.

Does it happen every time or only occasionally?

Is there anything else you can share? Like could you give me a sample repo? Or would that involve too much work to cut down your stuff to be publicly accessible?

What plugins are you using alongside this?

**Comment by agtcovert** [comment]
Here's the versions we're using:
Serverless 1.32
serverless-aws-resource-names: 0.0.9
serverless-dependson-plugin: 1.1.1
serverless-plugin-split-stacks: ^1.6.0
serverless-plugin-tracing: 2.0.0

Unfortunately, I can't share the source repo, it's proprietary.  I will gladly do whatever you need to pinpoint the problem.  I will have to rerun our build a couple of times, but so far it seems to happen every time.

Let me know if there's there's anything I can share -- could probably redact the serverless.yml if it helped you.

Thanks.

**Comment by troybESM** [comment]
Updating to v1.7 and deleting the stack resolved this for me.

**Comment by dougmoscrop** [comment]
I have no idea what could have changed to fix this!

**Comment by troybESM** [comment]
My bet would be that it was the removal of the existing stack. Thanks for your work on this plugin, it is very useful.

**Comment by dougmoscrop** [comment]
Hmm, tearing it down and recreating it could have fixed it, though I'd prefer not to make you do that

**Comment by dougmoscrop** [comment]
Like the only reason this ought to happen is a stack has no physical ID: https://github.com/dougmoscrop/serverless-plugin-split-stacks/blob/cff226c6cef4f8876691a5114b7a849f952c3b07/lib/migrate-existing-resources.js#L19

@agtcovert if you look at the CloudFormation console do you see anything like this?

You might also use the aws cli to list/describe your stack and see what it returns?

**Comment by joebernard** [comment]
I ran into this issue today. Running `sls package --stage dev` worked. But trying `sls package --stage prod` returned the error reported here. It looks like the zip files were created in the `.serverless` directory, but not the json files. The error happened right after the console output "Serverless: Packaging service...".

Running `sls remove --stage prod` seems to have fixed the issue.

**Comment by rsshilli** [comment]
I had this problem. My stack had an ID. Deleting the stack and recreating it with Serverless fixed it.

Sorry, I removed some PII and the AWS account # from the below.

<img width="835" alt="image" src="https://github.com/user-attachments/assets/51f33e64-b6ab-4d24-9881-f86c4bb71fb8">

**Comment by rsshilli** [comment]
Well, upon deleting the stack, I discovered that there was an old Lambda Layer in the configuration that shouldn't have been there (those libraries got merged into another Lambda Layer). So I ended up in the exact same spot. I had to delete that non-existent layer from my `Serverless.yml` file, the redelete the CF stack and then everything worked.
