### ISSUE TITLE
Re-Creating of the REST API on every update.

### ISSUE THREAD

**Issue by selected-pixel-jameson** [dougmoscrop/serverless-plugin-split-stacks#4]
Is there any work around for the Rest API being deleted and recreated with every deployment? Right now I have a script that pulls down the specific SDK package for the Rest API so that the API gets updated in my build process, but if the API ID is constantly changing the only solution is going to be to manually update that ID every time I update an endpoint.

**Comment by dougmoscrop** [comment]
We could try not migrating it; but I've seen the rest API get recreated just because - without doing anything (without even using this plugin). This will require more experimentation.

**Comment by selected-pixel-jameson** [comment]
Ok. I'm going to need to read up on CloudFormation and how it's actually working. I've relied heavily on the serverless functionality for this as of now. Maybe we could introduce an option to switch between the two types.

**Comment by dougmoscrop** [comment]
Is this no longer happening? Sorry I never got around to looking at it. I was pretty sure it was an AWS thing.

**Comment by selected-pixel-jameson** [comment]
I think that it might have just happened on the initial cut-over to using the plug-in. Hasn't been an issue since.
