### ISSUE TITLE
[v1.5.3] "ServerlessPluginSplitStacks.resolveMigration" not working

### ISSUE THREAD

**Issue by chata420** [dougmoscrop/serverless-plugin-split-stacks#40]
"root/stacks-map.js" file was read,
but dose'nt read function "ServerlessPluginSplitStacks.resolveMigration" in 1.5.3.
How can I fix this issue? Thanks.

**Comment by rkdavidson** [comment]
Mine does not appear to be working as well, in `[v1.5.2]`. Console logs in the root `stack-maps.js` show during deploy, but not console logs within `resolveMigration` method.

**Comment by dougmoscrop** [comment]
Should be fixed with 1.5.4 please try and let me know.

**Comment by chata420** [comment]
@dougmoscrop It works! Thanx!

**Comment by dougmoscrop** [comment]
Great, yeah I think this can be closed. Any further issues please reopen.
