### ISSUE TITLE
Unable to Delete Rest API that is mapped to a custom domain

### ISSUE THREAD

**Issue by selected-pixel-jameson** [dougmoscrop/serverless-plugin-split-stacks#5]
When running a deploy for a Rest API if that API is using a custom domain the stack deleting fails because all of the base paths must be removed before it can be deleted. However, it did delete all of the resources. 

It would be nice to have an option to make is o the current API doesn't get deleted when deploying so that you can gracefully switch from the old API to the new one without losing service.

**Comment by dougmoscrop** [comment]
How are you managing the DomainName?

If you associated it in the console/manually, you would have to undo this before the removal. If you are using my plugin `serverless-plugin-custom-domain`, it does this for you.

If you're using the new CloudFormation feature that launched yesterday, I have not had a chance to test with that :)

**Comment by selected-pixel-jameson** [comment]
Will give the custom domain a try and see if that resolves my issues.

**Comment by dougmoscrop** [comment]
I hope it worked out for you, please feel free to reopen if it did not!
