### ISSUE TITLE
Migration Strategies default change

### ISSUE THREAD

**Issue by maheshpj** [dougmoscrop/serverless-plugin-split-stacks#50]
Hi @dougmoscrop ,
Thanks for the awesome plugin! it made our life simple. We tested this plugin with our serverless deployments and worked great!
Just wanted to know one thing, in Migration Strategies you have mentioned that Per Lambda - This defaults to off in 1.x but will switch to enabled by default in 2.x.
Is there any specific reason to change the default behavior? 

Thanks,
Mahesh

**Comment by dougmoscrop** [comment]
Good question. Well it seemed to me that if we could group things for a given Lambda together, then when you remove a function it should be easy to remove the nested stack, and likewise assing a function adds a stack - this seemed like an easier to think about.

That said it's not so easy to group thigs reliably per function. I don't know about the change in defaults anymore :)

2.0 would be a way out too, I'm very swamped and not looking to shake things up just to create more work.

That said, if it did happen, the upgrade path can be just to turn off that strategy. But then I don't know why bother to have 2.0.

**Comment by dougmoscrop** [comment]
Picking a strategy is pretty important; I wonder if for `2.0` it should default to all strategies _off_ and require that they be explicit selected so that users know what they're getting in to.

**Comment by dougmoscrop** [comment]
I am going to go with ^ this idea for 2.0,  Everything will be off, running Serverless with no configuration will throw an error directing the user to documentation so that they make a very informed decision about their splitting strategy before getting themselves locked in or having to spend more time debugging.
