### ISSUE TITLE
Failed with serverless-plugin-warmup

### ISSUE THREAD

**Issue by pankajku** [dougmoscrop/serverless-plugin-split-stacks#51]
A life saver plugin! Thank you for creating this.

This (version 1.6.0) worked great for me with perType option but I had to comment out serverless-plugin-warmup. With the warmup plugin, I am getting this error:

```
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
..................................................................................
Serverless: Operation failed!
 
  Serverless Error ---------------------------------------
 
  An error occurred: WarmUpPluginLogGroup - /aws/lambda/security-pankajk-warmup-plugin already exists.
```
I tried changing the order of plugins in `serverless.yml` file:

```
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-plugin-split-stacks
  - serverless-plugin-warmup
```
and

```
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-plugin-warmup
  - serverless-plugin-split-stacks
```
but this didn't help. Only thing that worked was to completely take out the warmup plugin.

Other thing I noticed is that the base CF stack is not removed when the error was encountered.

**Comment by dougmoscrop** [comment]
Are you adding this plugin to an existing stack? 

The problem can be because Cloud formation doesn't understand "moving" a resource. 

Can you try a deployment with a new --stage for testing? 

I will take a look when I get some free time tol

**Comment by pankajku** [comment]
Tried with a new test stack — “serverless remove” the existing one and verified removal via CF console.

I suspect the warmup plugin is creating loggroup with the same name in both sub stacks.
