### ISSUE TITLE
"Embedded stack [...] was not successfully created: The following resource(s) failed to create: [..., ..., ...]

### ISSUE THREAD

**Issue by mhotchen** [dougmoscrop/serverless-plugin-split-stacks#52]
Hey there,

I have an existing stack with one function without your plugin installed or configured. The function has no events as input although having tested with and without events this makes no difference.

The current version of your plugin I'm using is `serverless-plugin-split-stacks@1.6.0` but I initially encountered this issue on 1.3.2 (the oldest version I've used). I have also tested running the serverless deploy command using both v6.10.3 and v10.10.0 of nodejs (on Ubuntu 18.04). The serverless runtime that I've targetted is nodejs6.10 on AWS. The serverless installation I have locally is version 1.3.2 for both v6 and v10 of nodejs.

After setting up and deploying a function using serverless I update my configuration with the following:

```yaml
plugins:
  - serverless-plugin-split-stacks
custom:
  splitStacks:
    perFunction: true
    perType: false
```

And of course have the package installed via NPM (a local installation, not global).

Here is the command I issue once I've installed your plugin and the response (with SLS_DEBUG set to true):

```bash
$ serverless deploy --stage dev
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: [serverless-plugin-split-stacks]: Summary: 3 resources migrated in to 1 nested stacks
Serverless: [serverless-plugin-split-stacks]:    Resources per stack:
Serverless: [serverless-plugin-split-stacks]:    - (root): 3
Serverless: [serverless-plugin-split-stacks]:    - [REDACTED]NestedStack: 3
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (22.2 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
........
Serverless: Operation failed!
 
  Serverless Error ---------------------------------------
 
  An error occurred: [REDACTED]NestedStack - Embedded stack arn:aws:cloudformation:[REDACTED] was not successfully created: The following resource(s) failed to create: [[REDACTED]LogGroup]. .
 
  Stack Trace --------------------------------------------
 
ServerlessError: An error occurred: [REDACTED]NestedStack - Embedded stack arn:aws:cloudformation:[REDACTED] was not successfully created: The following resource(s) failed to create: [[REDACTED]LogGroup]. .
    at provider.request.then (/home/[REDACTED]/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:112:33)
From previous event:
    at AwsDeploy.monitorStack (/home/[REDACTED]/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:26:12)
    at provider.request.then (/home/[REDACTED]/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:95:30)
From previous event:
    at AwsDeploy.update (/home/[REDACTED]/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:95:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/home/[REDACTED]/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:112:12)
From previous event:
    at AwsDeploy.updateStack (/home/[REDACTED]/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:106:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/home/[REDACTED]/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:129:39)
From previous event:
    at Object.aws:deploy:deploy:updateStack [as hook] (/home/[REDACTED]/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:125:10)
    at BbPromise.reduce (/home/[REDACTED]/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/home/[REDACTED]/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.spawn (/home/[REDACTED]/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:408:17)
    at AwsDeploy.BbPromise.bind.then (/home/[REDACTED]/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:95:48)
From previous event:
    at Object.deploy:deploy [as hook] (/home/[REDACTED]/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:91:10)
    at BbPromise.reduce (/home/[REDACTED]/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/home/[REDACTED]/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/home/[REDACTED]/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/home/[REDACTED]/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/home/[REDACTED]/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/home/[REDACTED]/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/bin/serverless:43:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           10.10.0
     Serverless Version:     1.32.0
```

It is not consistent with what resource it fails at. The resource type varies as well, especially once I ramp up the number of functions I try to run this configuration against. \*LambdaFunctionRole, \*LogGroup and ApiGatewayResource\* have all come up at the same time, for different resources. It will be (seemingly) random resources and resource groups that 'cause' the error each time although with just one Lambda it seems to always be the *LogGroup resource that fails.

I already use your plugin with the default stack per resource type configuration and it works great but I recently hit the limit on role policy length for the serverless Lambda role so wanted to additionally add the `serverless-plugin-custom-roles` plugin to have a role per function. This meant I needed to split my configuration further and if I can use a stack per Lambda that would make my life super easy for the foreseeable future.

This is a very useful plugin btw. If you want more information I'd be happy to provide it but I'm new to the serverless framework so I'm not sure what's useful to you right now, or even if it's a bug and not me doing something stupid (I think stupidity is more likely but I've been fighting this for a couple of days now and don't understand what I've done wrong).

I have tried to do this on an existing stack with more than 200 functions by changing the config for your plugin without adding or removing functions. Then I tried stripping back the config to ~180 functions and removing your plugin before trying to re-enable the plugin with the above configuration before finally moving all the way down to a single function.

**Comment by mhotchen** [comment]
Hey,

I just want you to know that I'm resolving this by extracting parts of my existing service out in to separate serverless services so if this is me doing something wrong you don't need to explain what, you can simply close the ticket and ignore me :)

Thanks again for the plugin. Even if I don't use the stack-per-Lambda I will continue to use the default configuration and will continue to find it extremely useful! If you suspect this is a bug then I will be happy to put the time in to helping you resolve it in any way I can.

**Comment by dougmoscrop** [comment]
Hey, yeah splitting it is always the best choice. Even with this plugin, it only buys you a bit more runway (which some might call "rope")

`perFunction` is .. experimental. I've never used it myself, but it was how I intended this plugin to work when I first started creating it, except time pressures made me fall back to perType. 

Debugging issues like this benefits from having the CloudFormation output itself, it will say which resources failed and why, but you have to catch them before the stacks are deleted/hidden from the UI (it requires refreshing/watching CF as it goes and fails).

Does the problem happen when you deploy a completely new stack? Like if you do `sls deploy --stage=foobarbaz`, does that fail?

Any changes in configuration basically require removing and redeploying the stack to be guaranteed to work; though this plugin does try to "preserve" resources that were migrated such that you can change the strategy.. it's always best effort. CloudFormation is very finnicky.

**Comment by mhotchen** [comment]
> CloudFormation is very finnicky.

So I'm learning! After my experiments with your plugin it failed to delete some resources then refused to deploy because "the resource already exists" haha.

I haven't brought my work laptop home today but I will tomorrow and I'll experiment with a new stack and try and get you a CloudFormation output.

Thanks for the speedy response. I like your original intention with this but totally understand your time is finite. I'll try to help you get there though, I'd love to be able to split my stack that way so I can still use a role per Lambda enabling me to be more selective of permissions.

**Comment by mhotchen** [comment]
Actually saying that I think you've covered what I wanted to say at the bottom. It could be moved up to where you show the config example but I think you've done pretty much everything you can here. You're welcome to close this ticket and thank you for your time.

**Comment by dougmoscrop** [comment]
A PR for improving the README is certainly welcome!

For what it's worth you should be able to do role-per-function without changing the split type - per function certainly looks cleaner, but what goes wrong when you try with perType? We use `serverless-plugin-custom-roles` with spilt stacks ourselves. One thing may be that you are overflowing the 200 resource limit of a nested stack because of all the permissions. You can add a `stacks-map.js` file to the root of your project that looks like:

```js
'use strict';

module.exports = {
	'AWS::Lambda::Permission': {
		destination: 'Permissions',
		allowSuffix: true
	}
};
```

All this does is allow more than one nested stack for Permissions. It will create `Permissions`, `Permissions2`, etc. Don't ask me why allowSuffix isn't true by default, I can't remember :) I was probably just trying to be cautious. It might be worth changing it to default to true and opt-out for known problematic resource types (if any?!). It has it's own challenge where we can't "re-pack" things, so if you balloon up to say 300 permissions in to two stacks, then remove some functions, the ones that were put in to `Permissions2` have to stay there (can't migrate resources around). New things will be put in to the first stack that has room so it's not the end of the world, but it all goes back to CF not supporting migrating resources.

**Comment by mhotchen** [comment]
> One thing may be that you are overflowing the 200 resource limit of a nested stack because of all the permissions.

This is exactly what happened and what sent me down this rabbit hole :) I will make some changes to the README tomorrow and send you a PR. I will also let you know how I get on with your suggested `stacks-map.js`, thank you for that :)

After all of this discussion I am really glad I opted for Terraform over CF. You've done amazing work managing to make this plugin work so well given how unwieldy CF is.

**Comment by dougmoscrop** [comment]
Yeah, we elected to use a hybrid approach where we manage our "data" or other persistent infrastructure (queues, etc) with Terraform, and our "app" layer with Serverless so we can, if necessary, easily tear down and redeploy the app tier during some kind of off hour. It's not perfect but it's been OK to us. We've also experimented with using CF on one service but in a separate, isolated stack from thje main one (serverless-plugin-bootstrap) again to separate data and persistence from the app tier.

**Comment by mhotchen** [comment]
`tf-output` looks very interesting, I've been hard coding the ARNs and stuff. My approach has been similar to yours so far with regards to combining serverless and Terraform, with serverless only defining its own roles and permissions and terraform defining actual resources.

Man I really appreciate your work, it's like you've hit every problem I'm going to be facing and built a solution just for me :)

It's going to take a while for me to have like a good rhythm with all of this but your open source projects align very well with my requirements so I'm looking forward to using some of the other stuff you offer as well!

**Comment by KanesYang** [comment]
Hi Matthew, I met the same problem here, but I didn't get the ideas for these. Would you mind sharing your stack-map.js code with me? Thanks.

**Comment by mhotchen** [comment]
Hi @KanesYang sorry for the delay. In the end I never used the `stack-map.js` file suggested since I've managed to slowly break this single large serverless project in to several smaller ones.

I'm happy with this approach so far; I'm still in transition but most of the code is in small serverless services now and my workflow has improved because of it.

**Comment by suryacaprice** [comment]
is there any solution to this?

**Comment by jordizle** [comment]
Make sure any old log groups are deleted before you try to deploy your stack.
