### ISSUE TITLE
Sub Nested Stacks

### ISSUE THREAD

**Issue by RyanCodes** [dougmoscrop/serverless-plugin-split-stacks#54]
Hello! Is there currently a way to define sub nested stacks of an already nested stacked with this plugin?

- root
--- Nested Stack A (child of root)
----- Nested Stack B (child of Nested Stack A)

Similar to the AWS diagram found here 
<img width="321" alt="screen shot 2018-10-17 at 4 39 50 pm" src="https://user-images.githubusercontent.com/3864816/47114995-4b169d00-d22b-11e8-9f72-f7df232c760d.png">

Thanks a bunch!

**Comment by RyanCodes** [comment]
@dougmoscrop I have lambda functions that depend on other resources in other nested stacks so when bringing all AWS::Lambda::Function type into their own nested stack instead of the root stack I get circular reference errors

**Comment by dougmoscrop** [comment]
Oh I see, it would have to be that those resources are also dependant on a Lambda, then. At least I think.

The answer is it should be, but it's not quite supported, I will fix this.

**Comment by RyanCodes** [comment]
awesome! ty

**Comment by RyanCodes** [comment]
@dougmoscrop do you know a typical time frame when this feature could show up?

**Comment by RyanCodes** [comment]
@dougmoscrop when you say migration function returns false explicitly  what do you mean?

**Comment by dougmoscrop** [comment]
You have to use the "custom" support, and add a `stacks-map.js` file in your project root that exports a function

```js
module.exports = (resource, logicalId) => {
  if (logicalId === 'MyFunctionThatShouldNotBeMigrated') {
    return false
  }
  // undefined means move on to other strategy, such as perType
};
```

**Comment by RyanCodes** [comment]
lgtm thanks
