### ISSUE TITLE
Increase the attempts to get the stack summary.

### ISSUE THREAD

**Issue by JaderCM** [dougmoscrop/serverless-plugin-split-stacks#55]
Could you increase the attempts to get the stack summary at utils.getStackSummary please?

I'm reaching this limit few times and my deploy fail with "Retry limit exceeded".

The value that works for me is 50 (instead the 5 in the current code).

https://github.com/dougmoscrop/serverless-plugin-split-stacks/blob/826bb867271fbcf51e34fd6613546539febcdf46/lib/utils.js#L261

**Comment by dougmoscrop** [comment]
bumped to 10, if this does not work please reopen, but anything higher is gonna be a lot of waiting!
