### ISSUE TITLE
Error occurred when deploy

### ISSUE THREAD

**Issue by KanesYang** [dougmoscrop/serverless-plugin-split-stacks#59]
The scenario is: 
In my previous deploy, I use the default configuration which is   `  perFunction: false
    perType: true `, but I still got the 200 resource exceeding error. So I modify the config to 
`    perFunction: true    perType: true`. Then I got the error like: 
` 
  An error occurred: DailyDashscheduleDashreportNestedStack - Embedded stack arn:aws:cloudformation:us-east-1:${ARNNAME}:stack/${projectName}-DailyDashscheduleDashreportNestedStack-7V01KEDLHJ9X/a66c33f0-4cc8-11e9-a380-0a456a010dd4 was not successfully created: The following resource(s) failed to create: [DailyDashscheduleDashreportLambdaFunctionRole, DailyDashscheduleDashreportLogGroup]. .
 `

What is the proper way to solve this? By advance usage by Stack-map.js or something else?

Appreicate to help of anykinds.

**Comment by dougmoscrop** [comment]
Is this a fresh deploy? CloudFormation really does not support moving resources around, so if you are going to change the migration 'strategy' you often need to remove + redeploy your stack.

If this is a fresh deploy, I think I need to see more details about the failure. You'd have to go to the CloudFormation console and look at the "Events" section which will have details about why those resources are failing to create.

You may also want to leave `perFunction: false` and yes as you said, modify stacks-map to do more custom routing.

**Comment by KanesYang** [comment]
@dougmoscrop  Great thanks for your response! 
If fresh deploy is the first time deployment, then no. I have deployed my app more than 40 times, everything works fine while I am using the default setting until it showed the error of exceeding 200 resources in the root stack. Thanks for your advice and amazing work on this and other serverless plugins. I will try to remove all the resource and recreate everything again.

**Comment by KanesYang** [comment]
Problem solved, thanks
