### ISSUE TITLE
CloudFormation - CREATE_FAILED - AWS::CloudFormation::Stack - APINestedStack

### ISSUE THREAD

**Issue by eduardoamills** [dougmoscrop/serverless-plugin-split-stacks#65]
Hello
I'm trying to execute this command, but it always returns this error:

`CloudFormation - CREATE_FAILED - AWS::CloudFormation::Stack - APINestedStack`

My application is growing, I do not know how to make this work.

The serverless.yml

[serverless.yml.zip](https://github.com/dougmoscrop/serverless-plugin-split-stacks/files/3251011/serverless.yml.zip)

And the complete output is 

`$ sls deploy --stage prod -v
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: [serverless-plugin-split-stacks]: Summary: 124 resources migrated in to 3 nested stacks
Serverless: [serverless-plugin-split-stacks]:    Resources per stack:
Serverless: [serverless-plugin-split-stacks]:    - (root): 165
Serverless: [serverless-plugin-split-stacks]:    - APINestedStack: 44
Serverless: [serverless-plugin-split-stacks]:    - PermissionsNestedStack: 40
Serverless: [serverless-plugin-split-stacks]:    - VersionsNestedStack: 40
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - phinics-prod
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - phinics-prod
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service phinics.zip file to S3 (31.15 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - phinics-prod
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GetNotificationLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GetStudyLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::DynamoDB::Table - InstitutionsDynamoDBTable
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GetPlanLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GetEventByIdLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::DynamoDB::Table - NotificationDynamoDBTable
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - CreateUserLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GetUserLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - UpdatePlanLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - DeleteUserLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - DeleteStudyLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - GetNotificationListLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::DynamoDB::Table - StudyDynamoDBTable
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - DownloadStudyLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - ResendverifyLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - UpdateNotificationLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CreateStudyLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - UnBlockUserLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::DynamoDB::Table - ProffesionalsDynamoDBTable
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - UsersListLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::DynamoDB::Table - PersonsDynamoDBTable
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - DeleteEventLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GetEventsListLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - EditStudyLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GetProfileLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - GetNotificationLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - EditEventLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ListPlanLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - GetPlanLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GetNewNotificationLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - UpdateUserLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GetPersonsLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::DynamoDB::Table - PlansDynamoDBTable
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - APINestedStack
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GetHistoryLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - EditEventLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - EditStudyLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CreateNotificationLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ResetUserPasswordLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::DynamoDB::Table - UsersDynamoDBTable
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - DeletePersonLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - ListPlanLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GetPersonLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - UpdatePersonLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - UpdateUserLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - UploadStudyLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - GetPersonsLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::DynamoDB::Table - EventDynamoDBTable
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - LoginUserLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - ResetUserPasswordLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ForgottenpasswordLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - DeletePersonLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - GetHistoryLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - CreateNotificationLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - GetPersonLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - UploadStudyLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - BlockUserLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - UpdatePersonLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - VerifyUserLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - AddPersonLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - DeleteNotificationLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CreateEventLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CreatePlanLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - DeleteEventLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CreateStudyLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GetEventByIdLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::DynamoDB::Table - CountersTable
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - UsersListLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - DeleteUserLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::DynamoDB::Table - StudyDynamoDBTable
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - ForgottenpasswordLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GetEventsListLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - UpdateNotificationLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - VerifyUserLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - DeleteNotificationLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GetProfileLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - BlockUserLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GetUserLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - CreateStudyLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - DeleteEventLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - LoginUserLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - CreateEventLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - GetEventByIdLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - DeleteUserLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GetNewNotificationLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - UpdateNotificationLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - UsersListLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - GetEventsListLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - CreatePlanLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - GetProfileLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GetStudyLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - GetUserLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - GetNewNotificationLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - AddPersonLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - GetStudyLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::DynamoDB::Table - CountersTable
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - AddPersonLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - APINestedStack
CloudFormation - CREATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_FAILED - AWS::CloudFormation::Stack - APINestedStack
CloudFormation - CREATE_FAILED - AWS::DynamoDB::Table - PlansDynamoDBTable
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - UsersListLambdaFunction
CloudFormation - CREATE_FAILED - AWS::DynamoDB::Table - StudyDynamoDBTable
CloudFormation - CREATE_FAILED - AWS::DynamoDB::Table - PersonsDynamoDBTable
CloudFormation - CREATE_FAILED - AWS::DynamoDB::Table - ProffesionalsDynamoDBTable
CloudFormation - CREATE_FAILED - AWS::Lambda::Function - UsersListLambdaFunction
CloudFormation - CREATE_FAILED - AWS::DynamoDB::Table - CountersTable
CloudFormation - CREATE_FAILED - AWS::DynamoDB::Table - UsersDynamoDBTable
CloudFormation - CREATE_FAILED - AWS::DynamoDB::Table - InstitutionsDynamoDBTable
CloudFormation - CREATE_FAILED - AWS::DynamoDB::Table - EventDynamoDBTable
CloudFormation - CREATE_FAILED - AWS::Lambda::Function - GetNotificationListLambdaFunction
CloudFormation - CREATE_FAILED - AWS::DynamoDB::Table - NotificationDynamoDBTable
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - phinics-prod
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - phinics-prod
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - UploadStudyLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - ListPlanLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - GetEventsListLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - GetNewNotificationLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - DeleteStudyLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - GetPersonLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - EditEventLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - GetProfileLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - GetNotificationLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - DeleteEventLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - ForgottenpasswordLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - GetUserLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::CloudFormation::Stack - APINestedStack
CloudFormation - DELETE_IN_PROGRESS - AWS::DynamoDB::Table - EventDynamoDBTable
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - EditStudyLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::DynamoDB::Table - CountersTable
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - LoginUserLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - DownloadStudyLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - DeleteNotificationLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - DeletePersonLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - BlockUserLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Function - GetNotificationListLambdaFunction
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Function - UsersListLambdaFunction
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - ResetUserPasswordLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - GetHistoryLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - UpdatePlanLogGroup
CloudFormation - DELETE_SKIPPED - AWS::DynamoDB::Table - ProffesionalsDynamoDBTable
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - ResendverifyLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - GetPersonsLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::DynamoDB::Table - StudyDynamoDBTable
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - CreateStudyLogGroup
CloudFormation - DELETE_SKIPPED - AWS::DynamoDB::Table - InstitutionsDynamoDBTable
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - UpdateUserLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - AddPersonLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - CreateNotificationLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::DynamoDB::Table - NotificationDynamoDBTable
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - CreatePlanLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - GetPlanLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - UnBlockUserLogGroup
CloudFormation - DELETE_SKIPPED - AWS::DynamoDB::Table - PersonsDynamoDBTable
CloudFormation - DELETE_SKIPPED - AWS::DynamoDB::Table - PlansDynamoDBTable
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - GetEventByIdLogGroup
CloudFormation - DELETE_SKIPPED - AWS::DynamoDB::Table - UsersDynamoDBTable
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - VerifyUserLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - UpdatePersonLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - CreateEventLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - GetStudyLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - GetEventsListLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - UploadStudyLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - ListPlanLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - GetPersonLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - GetNewNotificationLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - CreateUserLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - DeletePersonLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - CreateEventLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - CreateUserLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - UpdateNotificationLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - DeleteUserLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - DeleteStudyLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - EditStudyLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - EditEventLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - DeleteNotificationLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - GetProfileLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - DownloadStudyLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - ForgottenpasswordLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - LoginUserLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - GetNotificationLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - DeleteEventLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - UpdatePlanLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - GetUserLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - GetHistoryLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - CreatePlanLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - ResendverifyLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - CreateNotificationLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - GetPersonsLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - BlockUserLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - GetPlanLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - ResetUserPasswordLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - GetEventByIdLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - CreateStudyLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - AddPersonLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - UnBlockUserLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - UpdatePersonLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - VerifyUserLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - UpdateUserLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - GetStudyLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - GetNotificationListLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - UsersListLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - UpdateNotificationLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - GetNotificationListLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - DeleteUserLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - UsersListLogGroup
CloudFormation - DELETE_COMPLETE - AWS::CloudFormation::Stack - APINestedStack
CloudFormation - DELETE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - DELETE_COMPLETE - AWS::DynamoDB::Table - NotificationDynamoDBTable
CloudFormation - DELETE_COMPLETE - AWS::DynamoDB::Table - StudyDynamoDBTable
CloudFormation - DELETE_COMPLETE - AWS::DynamoDB::Table - EventDynamoDBTable
CloudFormation - DELETE_COMPLETE - AWS::DynamoDB::Table - CountersTable
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - phinics-prod
Serverless: Operation failed!
Serverless: View the full error output: https://us-west-2.console.aws.amazon.com/cloudformation/home?region=us-west-2#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-west-2%3A121770887788%3Astack%2Fphinics-prod%2F503adf50-8697-11e9-af5f-027fe4f7c9fc
 
  Serverless Error ---------------------------------------
 
  An error occurred: APINestedStack - Embedded stack arn:aws:cloudformation:us-west-2:121770887788:stack/phinics-prod-APINestedStack-15JUKI9WEGC42/7d5ecfa0-8697-11e9-9ef7-0211d8bec7e2 was not successfully created: The following resource(s) failed to create: [ApiGatewayResourceApiUserForgottenpassword, ApiGatewayResourceApiUserMembers, ApiGatewayResourceApiUserLogin, ApiGatewayResourceApiNotificationIdVar, ApiGatewayResourceApiUserResendverify, ApiGatewayResourceApiEventList, ApiGatewayResourceApiStudyUpload, ApiGatewayResourceApiAdminUser, ApiGatewayResourceApiPersonPersonVar, ApiGatewayResourceApiEventIdVar]. .
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     linux
     Node Version:           8.10.0
     Serverless Version:     1.40.0
`
I hope that you can help me

**Comment by dougmoscrop** [comment]
You gotta pull the full output from the AWS console, look at the events.

Are you removing/redeploying? You should do that the first time you use this plugin

**Comment by eduardoamills** [comment]
Hello, I will try again and I will put a screenshot of AWC console, I am removing and redeploying every time on development, I started the project with this plugin, it has worked well many times, but now besides that error, it also throws that the table already exists.

I'm a little lost, I do not understand the AWS console events well enough to determine what happened.
 My serverless.yml is growing very fast...

regards

**Comment by eduardoamills** [comment]
Hello attached part of AWS console events.

![image](https://user-images.githubusercontent.com/5342828/58919682-5a3c5380-8705-11e9-9887-052d9da1927d.png)

**Comment by dougmoscrop** [comment]
Ya you gotta get the events from that stack it's a separate set of events

**Comment by eduardoamills** [comment]
How can I do that?

**Comment by eduardoamills** [comment]
Hi

I resolved my issue in other way.

The real problem was "Error when renaming path variable" but in the logs and console not showed.
I deployed serverless.yml in several parts, in a moment the real issue was reveal, after fix that, the complete stack was deployed successfully

**Comment by dougmoscrop** [comment]
Yes, sorry I was not able to help more, super busy; but glad you got it sorted out.

Amazons developer experience with CloudFormation has a long road ahead..
