### ISSUE TITLE
stacks-map.js not read in root folder on 1.7.4

### ISSUE THREAD

**Issue by ajohnsen** [dougmoscrop/serverless-plugin-split-stacks#66]
Version 1.7.4 is ignoring the stack-map.js file that is in the root serverless project folder, i downgraded to version 1.7.3 and it worked just fine.

**Comment by spenchev** [comment]
Same issue here.

**Comment by dougmoscrop** [comment]
Got it, sorry, fixing

**Comment by dougmoscrop** [comment]
Fixed in 1.7.5
