### ISSUE TITLE
cannpt find module stacks-map.js

### ISSUE THREAD

**Issue by AlexSun98** [dougmoscrop/serverless-plugin-split-stacks#73]
Hi all, I'm using version 1.55. but I saw the error occurred during serverless deploy command. any idea? thanks

**Comment by evdh** [comment]
I had the same on 1.7.0 but upgrading to 1.8.0 fixed it

**Comment by dougmoscrop** [comment]
Hey sorry, yeah can you just update to the latest and try again?  If you still have the issue please reopen.
