### ISSUE TITLE
perFunction not solving resource limit issue

### ISSUE THREAD

**Issue by craig-dae** [dougmoscrop/serverless-plugin-split-stacks#96]
We have been using `perType`, but reached our new resource limit. So we switched to `perFunction`, expecting this to extend our limit. However, each nested stack only contains one resource, and our root stack is at 216 resources. This is after adding only one function to our stack, which use to deploy correctly with `perType`

We are using these plugins: 
```
plugins:
  - serverless-iam-roles-per-function
  - serverless-plugin-split-stacks
  - serverless-python-requirements
```

I suspect that iam-roles-per-function isn't playing nicely with split-stacks. 

```Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Packaging Python Requirements Lambda Layer...
Serverless: [serverless-plugin-split-stacks]: Summary: 157 resources migrated in to 42 nested stacks
Serverless: [serverless-plugin-split-stacks]:    Resources per stack:
Serverless: [serverless-plugin-split-stacks]:    - (root): 215
Serverless: [serverless-plugin-split-stacks]:    - APINestedStack: 29```

We can't move any more functions out of this serverless.yml into another one, because they all share the same base path. Can anyone give any advice on how to continue?

Thanks!

**Comment by dougmoscrop** [comment]
When you say switches do you mean you tore down the stack and redeployed? Otherwise the change in strategy will only apply to new resources

**Comment by craig-dae** [comment]
Should have tried that first. Thanks!
```
Serverless: [serverless-plugin-split-stacks]:    - (root): 71
```

**Comment by tvb** [comment]
@craig-dae those 71 recourses in your root stack are mostly IAM roles?
